### ISSUE TITLE
Error with password

### ISSUE THREAD

**Issue by anto582** [apoorva-dave/instagram-scrapper#1]
I try your script, but I have a password error because my password starts with $

INFO:root:Creating session
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    main()
  File "main.py", line 17, in main
    scrapper.create_session()
  File "/home/anto58/insta_scraper.py", line 17, in create_session
    L.login(self.username, self.password) # Login or load session
  File "/home/anto58/.local/lib/python3.8/site-packages/instaloader/instaloader.py", line 546, in login
    self.context.login(user, passwd)
  File "/home/anto58/.local/lib/python3.8/site-packages/instaloader/instaloadercontext.py", line 256, in login
    raise BadCredentialsException('Login error: Wrong password.')
instaloader.exceptions.BadCredentialsException: Login error: Wrong password.

**Comment by apoorva-dave** [comment]
In bash, $ is a special character so you will have to escape it using a '\\'. Example -
if your password is $abcd123! you can execute the script as:
`python main.py --password \$abcd123\! --username XXX`

Other way is to read the username and password from a config file
